finortho_fritage_echange_data:
    path:     /fritage/upload
    defaults: { _controller: FinorthoFritageEchangeBundle:Echange:index }


finortho_fritage_echange_identification_entreprise:
    path:     /fritage
    defaults: { _controller: FinorthoFritageEchangeBundle:Echange:connexion}
