finortho_fritage_echange_data:
    path:     /
    defaults: { _controller: FinorthoFritageEchangeBundle:Echange:index }

finortho_fritage_echange_download:
    path:     /download/{id}
    defaults: { _controller: FinorthoFritageEchangeBundle:Echange:download}

finortho_fritage_echange_erase:
    path:     /erase/{id}
    defaults: { _controller: FinorthoFritageEchangeBundle:Echange:erase}
