finortho_fritage_echange_data:
    path:     /fritage
    defaults: { _controller: FinorthoFritageEchangeBundle:Echange:index }


finortho_fritage_echange_home:
    path:     /
    defaults: { _controller: FinorthoFritageEchangeBundle:Echange:test }
