services:
    finortho_fritage_echange.check_double:
        class: Finortho\Fritage\EchangeBundle\Services\CheckDouble
        arguments: [@doctrine.orm.entity_manager]

    finortho_fritage_echange.user_uploads:
        class: Finortho\Fritage\EchangeBundle\Services\LastUploads
        arguments: [@doctrine.orm.entity_manager, @security.token_storage]
