services:
    finortho_fritage_echange.check_double:
        class: Finortho\Fritage\EchangeBundle\Services\CheckDouble
        arguments: [@doctrine.orm.entity_manager]

    finortho_fritage_echange.user_uploads:
        class: Finortho\Fritage\EchangeBundle\Services\LastUploads
        arguments: [@doctrine.orm.entity_manager, @security.token_storage]

    finortho_fritage_echange.session_handler:
        class: Finortho\Fritage\EchangeBundle\Services\SessionHandler
        arguments: [@session, @doctrine.orm.entity_manager]

    finortho_fritage_echange.namer:
        class: Finortho\Fritage\EchangeBundle\Services\FinorthoNamer
        arguments: [ @security.token_storage, @session, @swiftmailer.mailer.default, @doctrine.orm.default_entity_manager]

    finortho_fritage_echange.file_tree:
        class: Finortho\Fritage\EchangeBundle\Services\FileTree

    finortho_fritage_echange.preupload_listener:
        class: Finortho\Fritage\EchangeBundle\Services\PreUploadUser
        arguments: [@doctrine, @session]
        tags:
            - { name: kernel.event_listener,  event: oneup_uploader.pre_upload, method: onUpload }