finortho_admin_homepage:
    path:     /
    defaults: { _controller: FinorthoAdminBundle:MultiFile:index }

finortho_admin_new_user:
    path:     /users/new
    defaults: { _controller: FinorthoAdminBundle:UserManagement:addUser }

finortho_admin_delete_user:
    path:     /users/delete/{id}
    defaults: { _controller: FinorthoAdminBundle:UserManagement:deleteUser }

finortho_admin_list_users:
    path:     /users
    defaults: { _controller: FinorthoAdminBundle:UserManagement:listUser }

finortho_fritage_echange_pack:
    resource: "@FinorthoAdminBundle/Resources/config/routing/pack.yml"
    prefix:   /pack
