finortho_api:
    resource: "@FinorthoApiBundle/Resources/config/routing.yml"
    prefix:   /

finortho_admin:
    resource: "@FinorthoAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

finortho_fritage_echange:
    resource: "@FinorthoFritageEchangeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

oneup_uploader:
    resource: .
    type: uploader

#exigence_api:
#    resource: "@PBWApiBundle/Resources/config/routing.yml"
#    prefix:   /api