finortho_admin:
    resource: "@FinorthoAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

finortho_fritage_echange:
    resource: "@FinorthoFritageEchangeBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

oneup_uploader:
    resource: .
    type: uploader