finortho_fritage_echange:
    resource: "@FinorthoFritageEchangeBundle/Resources/config/routing.yml"
    prefix:   /fritage

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /fritage