produits:
    type: rest
    resource: "@FinorthoApiBundle/Controller/ProduitController.php"

packs:
    type: rest
    resource: "@FinorthoApiBundle/Controller/PackController.php"

messages:
    type: rest
    resource: "@FinorthoApiBundle/Controller/MessageController.php"

commandes:
    type: rest
    resource: "@FinorthoApiBundle/Controller/CommandeController.php"
